// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6FAroADnf4nqvbn1omM94zmFeyXWecEc',
    appId: '1:1056025366422:web:82f0959e9fd00d73ea97b7',
    messagingSenderId: '1056025366422',
    projectId: 'project-micro-journal',
    authDomain: 'project-micro-journal.firebaseapp.com',
    storageBucket: 'project-micro-journal.firebasestorage.app',
    measurementId: 'G-KFNH715LYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjeOoHFuihnPzi-JUVPXbfpv6wnMt_Gfk',
    appId: '1:1056025366422:android:7633395900288cbdea97b7',
    messagingSenderId: '1056025366422',
    projectId: 'project-micro-journal',
    storageBucket: 'project-micro-journal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs8vXEySSfmy52jrQ7iE_mxtgEajbhNjQ',
    appId: '1:1056025366422:ios:907dafae29ddaaeeea97b7',
    messagingSenderId: '1056025366422',
    projectId: 'project-micro-journal',
    storageBucket: 'project-micro-journal.firebasestorage.app',
    iosBundleId: 'com.masterboxer.projectmicrojournal',
  );
}
